### ISSUE TITLE
AttachmentsViewModel: remove workaround for handling random file name

### ISSUE THREAD

**Issue by codergrl** [Esri/data-collection-dotnet#11]
Currently the API generates a random file name and extension when an attachment is downloaded. A workaround is in place to create a copy of the file with the proper extension so it can be opened by Windows. This workaround should be removed once the API implements algorithm that doesn't change the file name.

**Comment by nCastle1** [comment]
[PR](https://github.com/Esri/data-collection-dotnet/pull/69)
