### ISSUE TITLE
'Invalid parameters' error when attaching new file

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#20]
After attaching a new image, saving the edits consistently throws the message:

![image](https://user-images.githubusercontent.com/25207711/55444549-b818b780-556b-11e9-961b-ba6f6cff8e6f.png)

Tapping 'OK' to acknowledge this error and then 'X' to cancel committing the edits still persists the would-be attachment in the list of attachments view.

Tapping 'X' in the upper right of the popup view dialog to dismiss it, and then re-querying the point still reveals the attachment until the application is closed and reopened.

**Comment by codergrl** [comment]
@mikewilburn Can't replicate this. Can you try testing it with the new version please

**Comment by mikewilburn** [comment]
After several attempts, I'm also no longer to able to reproduce this, so I'll close this one out.
