### ISSUE TITLE
UWP: Clicking 'X' to dismiss the sign-in dialog returns the error "Portal item type incorrect"

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#35]
I noticed on the `dev` branch that when the app is configured to view a web map that is not public, and when dismissing the sign-in dialog that appears by default, the map fails to load (which is expected), but cites an inaccurate error message.

![image](https://user-images.githubusercontent.com/25207711/58360274-cd5be500-7e3c-11e9-9119-732e9d91f8a2.png)

In this case, an incorrect 'Map failed to load' error is given:
![image](https://user-images.githubusercontent.com/25207711/58360211-68a08a80-7e3c-11e9-83a6-f7577ebdb830.png)

Signing in with valid credentials has no problem launching the expected web map.

**Comment by nCastle1** [comment]
This has been fixed:

![image](https://user-images.githubusercontent.com/29742178/59233014-99eabb80-8b9b-11e9-8f7c-99b5703ab17a.png)
