### ISSUE TITLE
Can we deploy this app onto Arcgis desktop application as well??

### ISSUE THREAD

**Issue by narnaneon** [Esri/data-collection-dotnet#37]
I would like to know if this app can be used only for online or pro?? 

Can we add this as a plugin into arcgis desktop??

**Comment by nCastle1** [comment]
The data collection app is designed as a standalone Windows app and is intended for use in field scenarios, where it would be used independently from ArcGIS Pro/Desktop.

There is no support for embedding the app as a Desktop/Pro plugin.

The project is open source, so you're free to use any part of the code that you find useful.

Does that answer your question?

**Comment by nCastle1** [comment]
I'm going to close this issue for now, please feel free to re-open if you have more questions.
