### ISSUE TITLE
UWP: logging a new tree point doesn't persist Species related record information

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#42]
When capturing a new tree point, I've run into several cases where selecting a related tree species does not save this information so that it's viewable outside of the edit session.

The same is also true of ArcGIS Online - the tree record doesn't appear to have a related Species record.

Here's a GIF showing the process of specifying a species, but which isn't available once the edit the saved:
![missing-species](https://user-images.githubusercontent.com/25207711/59071612-46fbc600-8874-11e9-852d-01cf862a1c2a.gif)

**Comment by nCastle1** [comment]
@mikewilburn I've got an idea about what's causing this and the fix likely involves some changes to how we do data binding. Those changes would likely have many conflicts with the open PRs, so I'll wait until all open PRs are closed before tackling this.

**Comment by nCastle1** [comment]
@mikewilburn LMK if you have some time on Monday to verify that the species behavior is indeed fixed by #58.

**Comment by mikewilburn** [comment]
I tried to vet this pretty thoroughly and am no longer seeing any instances - either when adding a new tree point, or editing an existing one - where providing related Species information isn't being persisted outside of the edit session.

Appears fixed to me!
