### ISSUE TITLE
UWP: use field alias in field validation message instead

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#43]
When an invalid value is entered for a field, a validation message appears which cites the name of the field. This provides useful context if the application gets extended/customized to support entry of field values outside of this dedicated UI.

Since these can be named completely independently and may not resemble each other at all, and because there could potentially be a large disparity between the name of a field and its alias, this would be more useful if the field alias was used in the message instead.

Here's an example:
![image](https://user-images.githubusercontent.com/25207711/59126097-102bbb80-8919-11e9-9473-6098fdaf7bc3.png)

In the default service used for this app, here's a list of field names & aliases that do not match:
![image](https://user-images.githubusercontent.com/25207711/59126743-a7ddd980-891a-11e9-88d3-7b378f14f452.png)

**Comment by nCastle1** [comment]
We're showing the exception text provided by the API. We'd need an API enhancement to improve this behavior.

**Comment by nCastle1** [comment]
Logged internal issue as dotnet-api/7600

**Comment by mikewilburn** [comment]
In that case, I think this one is fine to close. I'll mark it that it's behaving as designed for now.
