### ISSUE TITLE
UWP: downloading an offline map completes successfully but raises 'token required' error

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#54]
Even while logged in, downloading an offline map can throw this error after the download completes. (I haven't seen this consistently, but have run into it twice. If and when I can reproduce it more consistently, I'll update with specific steps.)

![image](https://user-images.githubusercontent.com/25207711/59541658-33291300-8eb7-11e9-99da-39f94e1ec729.png)

Note that clicking 'OK' on this message returns to the offline map and everything proceeds as expected. That I can tell, nothing about the offline map is impacted.

**Comment by nCastle1** [comment]
This is something I'd like to resolve, but will need to do some digging to find a clear repro; its possible this is related to a service issue that has since gone away, as I haven't seen it in ages.

**Comment by mikewilburn** [comment]
I also haven't seen it in ages. Let me see if I can repro as well, and then will comment in this issue.

If I'm unable, I think we'll be okay to close this.

**Comment by mikewilburn** [comment]
I've downloaded several offline maps today and not run into this behavior once. Closing.
