### ISSUE TITLE
UWP: Logging into the app is prevented

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#55]
I've stumbled across a case where I've become logged out of the app, but am prevented from logging back in. Attempting to do so automatically raises a 'Login unsuccessful' message:

![uwp-unable-to-log-in](https://user-images.githubusercontent.com/25207711/60143696-4f109c80-9774-11e9-99d1-00abbf0e5158.gif)

When and if I determine steps to reproduce this, I'll update this issue.

**Comment by nCastle1** [comment]
@mikewilburn LMK if you have time to verify #59 before UC. Thanks!

**Comment by mikewilburn** [comment]
@nCastle1 the trouble here is that I'm not sure how to first force the behavior where I become logged out of the app unknowingly. Do you know after how long the token is currently set to expire after it's initially generated?

**Comment by nCastle1** [comment]
@mikewilburn My understanding is that it is configured by Portal. For my own testing, I manually configured an expiration of 1 minute. I can provide a build like that for testing if you'd like.
