### ISSUE TITLE
Resolve minor UI inconsistencies between UWP and WPF

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#57]
I overlooked these while logging #34 and #40.

Whereas WPF provides consistent hover emphasis and tooltips for all buttons, UWP lacks these for a few, namely the `Add Related Record`, `Show Detail`, `Close [Dialog]`, and `Collapse [Dialog]` buttons:

<details><summary>WPF example</summary>
<p>

![2019-06-26 11 08 12](https://user-images.githubusercontent.com/25207711/60204909-c42bb280-9804-11e9-9047-fc0af9080ddd.gif)
</p>
</details>

<details><summary>UWP example</summary>
<p>

![2019-06-26 11 15 03](https://user-images.githubusercontent.com/25207711/60204905-c1c95880-9804-11e9-9f74-db8c3a53250c.gif)
</p>
</details>

It would be great to shore up these inconsistencies and add them to UWP as well.

**Comment by nCastle1** [comment]
@mikewilburn PR #60 opened

**Comment by mikewilburn** [comment]
Looks good! Just a few questions for clarification on what I should be seeing:
- did you remove the 'Collapse' button? I'm not seeing it any longer.
- neither the 'Show Detail' nor 'Add Related Record' button shows hovers emphasis. Should they?
- the 'Close' button shows emphasis, but it's gray and not orange like the others. Was this an oversight or intentional?

**Comment by nCastle1** [comment]
I did remove the collapse button - the feature didn't really make sense and isn't in the WPF version. It also caused a crash on some devices. 

There is a subtle emphasis on the show detail and add record buttons. I don't know if it would look good with the orange hover emphasis, but I can add it if that's what we want. 

I'm wondering if we might want to remove the orange hover emphasis altogether. It seems to be suppressing the built-in [reveal style](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal).

**Comment by mikewilburn** [comment]
Totally good with the collapse button removal. Your reasoning makes sense to me. Just wanted to make sure it was a conscious decision and not an unintended result of another change!

As for the hover emphasis, I think the most important thing above all is that we're consistent. If you're unsure whether the current orange looks right and/or think it distracts from what's recommended, then maybe we should remove it and revert back to that built-in style. I think you have good judgement so I'm cool with that!

P.S. 
> the built-in [reveal style](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal)  

Thanks for sharing that! I had no idea what that was.

**Comment by nCastle1** [comment]
Next steps: remove orange hover emphasis; should take a few hours at most.

**Comment by nCastle1** [comment]
PR open: https://github.com/Esri/data-collection-dotnet/pull/67

**Comment by mikewilburn** [comment]
PR #67  resolves these behaviors on UWP:
- [x] hover emphasis color is consistent throughout
- [x] tooltips appear for all the buttons
- [x] title is white on green

<details><summary>Here are examples GIFs:</summary>
<p>

![2019-10-09 16 54 52](https://user-images.githubusercontent.com/25207711/66528845-265bab00-eab6-11e9-8671-285ca42c25a7.gif)

![2019-10-09 16 52 42](https://user-images.githubusercontent.com/25207711/66528852-2fe51300-eab6-11e9-89dd-971c0063c41d.gif)
</p>
</details>
