### ISSUE TITLE
UWP: update icon configuration options to appear consistent with others

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-dotnet#62]
When pinning the UWP app to the Windows Start Menu, its icon presently takes up the entire tile and does not include a subtitle. Compared with how this is being handled by other apps, this looks a bit odd.

Here's a comparison with the Collector for ArcGIS app at each of the small, medium, wide, and large tile sizes:

![image](https://user-images.githubusercontent.com/25207711/61415913-fa5dce80-a8a6-11e9-8ac3-7099590660ea.png) ![image](https://user-images.githubusercontent.com/25207711/61415917-fd58bf00-a8a6-11e9-99c2-325cc947112b.png)

![image](https://user-images.githubusercontent.com/25207711/61415931-0184dc80-a8a7-11e9-9b64-e76a7ebe9f50.png) ![image](https://user-images.githubusercontent.com/25207711/61415939-047fcd00-a8a7-11e9-8b16-e5afce20a14c.png)

![image](https://user-images.githubusercontent.com/25207711/61415946-0b0e4480-a8a7-11e9-8163-2f11893f7fb4.png) ![image](https://user-images.githubusercontent.com/25207711/61415950-0ea1cb80-a8a7-11e9-8b0b-85c0a38c9439.png)

![image](https://user-images.githubusercontent.com/25207711/61415956-12cde900-a8a7-11e9-8fe6-a412e869f528.png) ![image](https://user-images.githubusercontent.com/25207711/61415965-15c8d980-a8a7-11e9-9c84-37a3808c2da2.png)

**Comment by nCastle1** [comment]
PR opened: https://github.com/Esri/data-collection-dotnet/pull/66

**Comment by mikewilburn** [comment]
Closing since this behavior has been verified and its PR merged into the `dev` branch.
